np = int(input('Digite um numero para ver sua tabuada: '))
print('___________')
print('{} x {:2} = {}'.format(np, 1, np * 1))
print('{} x {:2} = {}'.format(np, 2, np * 2))
print('{} x {:2} = {}'.format(np, 3, np * 3))
print('{} x {:2} = {}'.format(np, 4, np * 4))
print('{} x {:2} = {}'.format(np, 5, np * 5))
print('{} x {:2} = {}'.format(np, 6, np * 6))
print('{} x {:2} = {}'.format(np, 7, np * 7))
print('{} x {:2} = {}'.format(np, 8, np * 8))
print('{} x {:2} = {}'.format(np, 9, np * 9))
print('{} x {:2} = {}'.format(np, 10, np * 10))
print('___________')

