x = input('Digite qualquer coisa: ')
print('E numero:',x.isnumeric())
print('E letra:',x.isalpha())
print('E numero OU/E letra:',x.isalnum())
print('E espaço:',x.isspace())
print('E um simbolo:',x.isascii())
print('Tudo esta maisculo:',x.isupper())
print('Tudo esta minisculo:',x.islower())
print('E um decimal:',x.isdecimal())